include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning

linter:
  rules:
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    hash_and_equals: true
    package_api_docs: false
    slash_for_doc_comments: true
    throw_in_finally: true
    unrelated_type_equality_checks: true
    valid_regexps: true
