name: dropdown_search
description: Simple and robust Searchable Dropdown with item search feature, making it possible to use an offline item list or filtering URL for easy customization.
version: 1.0.0
homepage: https://github.com/kechankrisna
git: https://github.com/kechankrisna/dropdown_search
repository: https://github.com/kechankrisna/dropdown_search

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
